jfhbrook/node-ecstatic

- lib/ecstatic.js
This fixes an issue I hit using http-server to run a simple test site, and I can see others have reported this also (e.g. https://github.com/nodeapps/http-server/issues/122 ).
Basically, path.join is used in places (such as @ line 117: `url: path.join(encodeURIComponent(pathname), '/index.' + defaultExt)`), and this results in backslashes in the URL on Windows.  This causes failures in the decodePathname function, as it only handles forward slashes when breaking apart the paths.  This change simply handles backslashes as well as forward slashes to split the path before trying to decode the parts.  This fixes the issue for me.
Note the line called out above (117) looks suspect also, so the correct fix may actually be here.  For example, when just running 'http-server' and requesting the …
> Fix path splitting to account for Windows paths

- README.md
- lib/ecstatic.js
- lib/ecstatic/opts.js
- test/server-header.js
As the title says, this PR adds the ability to disable the 'Server' header for all responses that ecstatic handles.
> Add option to disable 'Server' header

- lib/ecstatic/showdir.js
I would like to use the *proxy-middleware* if the request cannot be resolved locally.
However right now `handleErrors = false` is ignored if `showDir` is set to `true` and the directory does not exists and displays a error page instead.
> Bugfix: `handleErrors` is ignored when using `showDir`

- lib/ecstatic.js
- test/enotdir.js
This happens when you specify a file that exists and try and use that as a directory.
Eg. `something/index.html/folder` where index.html is a file. This PR changes ecstatic to treat the error as a 404.
> Handle ENOTDIR as 404

- lib/ecstatic.js
- test/public/another-subdir/scripts.js
- test/union-multiple-folders-cases.js
- test/union-multiple-folders.js
And fixes weird issue with 404 status code.
The `res.statusCode` should always be check and adjusted in the `serve` method. Just set the `req.statusCode` in `statFile` and use it in `serve`.
Hope this makes sense. I added tests for multiple folder to serve. All test seem to work correctly.
Closes #136
> Add ability to use multiple instances of ecstatic

- lib/ecstatic.js
`src.pipe(dst)` doesn't close the source stream if the destination closes. this means that ecstatic will leaks file descriptors if the response closes before the file stream ends
> destroy the file stream if the response closes

- lib/ecstatic/showdir.js
- b[0]-a[0] returns NaN, so this is never valid in a sorting function
- reverted sorting order a-z (was z-a)
> correct sort ordering and also applied to dirs and lolwuts

- lib/ecstatic/showdir.js
- test/showdir-with-spaces.js
If a directory listing was requested for a directory with spaces in its name, already escaped url was combined with the file names.
Expected: subdir_with%20spaces\file_with%20space.html
Got:      subdir_with%2520spaces\file_with%20space.html
> Fixed double encoding in directory listings when directory name contains spaces

- lib/ecstatic.js
- test/process-env-port.js
As mentioned in #119, this allows the server to listen to the port given in process.env.PORT if the number is of sane value.
If no value is given in process.env.PORT or the port number is _not_ sane then the server listens on
``` opts.port || opts.p || 8000``` as usual.
*I chose sanity to be ports >1024 and =< 65536 based off [this list of well-know ports](http://www.webopedia.com/quick_ref/portnumbers.asp)
I wasn't really sure how to write test for this.  It seemed like an easy change but if test are needed I could see what I can do.
> added fallback to process.env.PORT

- LICENSE.txt
- lib/ecstatic/showdir.js
- lib/ecstatic/status-handlers.js
- test/html-reflection.js
- test/showdir-pathname-encoding.js
- test/showdir-search-encoding.js
The change I submitted in #142 was adequate to prevent XSS in Firefox, but potentially not in all browsers. Previous versions of Internet Explorer have aggressively sniffed `text/plain` content as `text/html` despite the header, and it may be possible to provoke this behaviour in current versions if compatibility modes are enabled. Bugs have also resulted in this behaviour in other browsers in some contexts, as recently as iOS 6 Safari. I'm not certain whether it's possible to trigger this for these specific error messages (I don't have a proof of concept), but in the interest of taking a conservative approach to security, I suggest replacing the `text/plain` responses with unencoded bodies with `text/html` responses with encoded bodies.
This PR also corrects two other locations where …
> Potential XSS mitigations and encoding corrections

- lib/ecstatic/showdir.js
- test/showdir-href-encoding.js
I happened to have a file with a '#' in the filename, and when using @indexzero's http-server (which uses ecstatic for autoIndex) the filename wasn't being properly encoded. This should fix that (as well as any files which use "; , / ? : @ & = + $" in the filename as well). Also updated a test that broke with the change.
> Use encodeuricomponent

- lib/ecstatic.js
Currently:
```
$ ecstatic --cors public -p 8000
```
will serve `./`, NOT `./public` because `--cors` gobbles up the `public` argument. With this patch, the above works as expected.
> boolean options

- lib/ecstatic.js
- lib/ecstatic/aliases.json
- lib/ecstatic/defaults.json
- lib/ecstatic/opts.js
On the back of #160, this patch fixes an issue where setting an option as boolean sets the value to `false` unless otherwise specified in minimist. I've factored the defaults from opts.js into defaults.json so they can be shared from opts.js and the bin script and also the aliases. Before the handleOptionsMethod was set to `false` even when `--cors` was turned on because of the boolean setting.
> more boolean handling

- lib/ecstatic/defaults.json
I missed `cors` in the default list, which was the whole reason behind the first patch!
With this patch:
```
$ ecstatic --cors public/ -p 8000
```
will finally work.
> set cors to false to enable booleanism on the command-line

- README.md
- lib/ecstatic.js
- lib/ecstatic/opts.js
- test/cache.js
Fixes #94
I didn't see any tests involving cache-control or I would have added to them.
> Allow using a function to set cache-control headers

- README.md
- lib/ecstatic/aliases.json
- lib/ecstatic/defaults.json
- lib/ecstatic/opts.js
- lib/ecstatic/showdir.js
Thought it'd be useful to be able to exclude dotfiles from directory listings. This came up when I wanted to use ecstatic to create a quick local server to share a directory of files with a non-technical coworker. It doesn't affect `../`links.
> Add opts.showDotfiles

- CONTRIBUTORS.md
- README.md
Adds showDotfiles to main opts example in README. Also took the opportunity to update the CONTRIBUTORS.
```js
var opts = {
root               : __dirname + '/public',
baseDir            : '/',
cache              : 3600,
showDir            : true,
showDotfiles       : true,
autoIndex          : false,
humanReadable      : true,
headers            : {},
si                 : false,
defaultExt         : 'html',
gzip               : false,
serverHeader       : true,
contentType        : 'application/octet-stream',
mimeTypes          : undefined,
handleOptionsMethod: false
}
```
> Add showDotfiles to main opts example in README.

- CONTRIBUTING.md
- README.md
I think the simplest way to overcome our tests, for malformed directory listings links, breaking git on Windows, is to educate Windows users about the caveat. This is my attempt to do so.
> Added documentation about cloning ecstatic on Windows - close #172

- test/process-env-port.js
Unless you want ecstatic to listen to no particular address, then 0.0.0.0 is wrong.
http://www.howtogeek.com/225487/what-is-the-difference-between-127.0.0.1-and-0.0.0.0/
*Fix failing test on Windows*
> fix wrong localhost on Windows - now passing

- lib/ecstatic.js
- test/illegal-access-date.js
node inherits a bug from v8 where some dates raise exceptions instead of returning an `Invalid Date` object:
```
$ node
> new Date('275760-09-12')
Fri Sep 12 275760 00:00:00 GMT-0400 (EDT)
> new Date('275760-09-13')
Invalid Date
> new Date('275760-09-23')
Invalid Date
> new Date('275760-09-24')
illegal access
> new Date('275760-10-13')
illegal access
> new Date('275760-10-14')
Invalid Date
> ^D
$ node -v
v4.2.1
```
Knowing this, it's possible to crash ecstatic by sending a malicious `If-Modified-Since` header:
```
$ mkdir /tmp/xyz
$ echo '<h1>doot doot</h1>' > /tmp/xyz/index.html
$ ecstatic -p 5000 /tmp/xyz &
[1] 11994
$ curl -H if-modified-since:275760-09-24 http://localhost:5000/index.html
/home/substack/projects/node-ecstatic/lib/ecstatic.js:280
if (modifiedSince && (new …
```
> Illegal access crash from if-modified-since header

- lib/ecstatic.js
- test/custom-content-type-json-string.js
This patch enables the following, for cases where maintaining a .types file is overkill:
`ecstatic ./data --port 1337 --mimeTypes '{ "application/x-my-type": ["x-mt"] }'`
> Allow setting mimeTypes via cli

- lib/ecstatic.js
- test/304.js
I recently noticed that I was only ever getting 200's from ecstatic and tracked the issue down to `stat.mtime` having millisecond resolution on my system, which is more than what's included in the date string sent in the last-modified header.
The test doesn't fail because it's not doing what I think browsers do and what the spec seems to be recommending:
> To get best results when sending an If-Modified-Since header field for cache validation, clients are advised to use the exact date string received in a previous Last-Modified header field whenever possible.
I updated the test accordingly and discovered it still didn't fail on my laptop, where mtimes seem to be lower resolution, but maybe it will fail at travis?
> Improve correctness and efficiency of cache validation code

- lib/ecstatic.js
- test/trailing-slash.js
When both `showDir` and `autoIndex` options are OFF we do not serve directories in any form. So if the client requests `/foo` and `foo` is a directory, we should NOT handle the request at all. It doesn't make sense to redirect them to `/foo/` because we won't be able handle that path either. This creates an un-necessary round-trip and perhaps more importantly it exposes details about our filesystem structure.
> Do not redirect / add trailing slash when showDir and autoIndex are off.

- CHANGELOG.md
- CONTRIBUTORS.md
- lib/ecstatic/show-dir/index.js
- lib/ecstatic/show-dir/styles.js
> Fix icon styles in showdir when text is wrapping in multiple lines

- CONTRIBUTORS.md
- lib/ecstatic/show-dir/styles.js
1. Using `background` instead of `background-image` will override previously set attributes such as `background-repeat: no-repeat` which is undesirable
2. Since the table is not automatically width-fixed, we have to disable line breaking in order to show the entire path (and permissions) in one line
> fixed CSS and layout

- .travis.yml
- package-lock.json
- package.json
This remove the node version of codecov and uses the bash version instead.
So the longer any nonsense codecov when doing local `npm test` also I put in an auto job flag for `tap`, so if you got multiple processors, it should speed up tests.
Hurry up and merge this in :) Then I can rebase #209 to master and we see if PR's adds or lower the coverage. But we need at least one coverage report in master before it works.
oh, and I also changed from lcov to clover reports - not sure what the difference is but I found an example with clover and codecov...
> Fix codecov

- lib/ecstatic.js
According to [RFC 2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html):
> 4.2 Message Headers
> ...
> The field-content does not include any leading or trailing LWS: linear white space occurring before the first non-whitespace character of the field-value or after the last non-whitespace character of the field-value. Such leading or trailing LWS MAY be removed without changing the semantics of the field value.
But if header `Range` doesn't contain \<range-end\>, but contains space after `-` → then `parseInt(' ', 10)` returns NaN and ecstatic responses with 416 Range Not Satisfiable.
Real client request and response example:
> Fix 416 if there are spaces in range header

- CONTRIBUTORS.md
- lib/ecstatic/etag.js
Hi there. According to [RFC7232 section 2.3.](https://tools.ietf.org/html/rfc7232#section-2.3), a valid etag value should be double-qouted and string between should contains no double quote character itself. While it doesn't seem to break any browser, it is kind of feeling weird each time I inspect the headers when I'm debuging some other things.
There're not much difference after this PR applied. the string is almost the same, only with the double qoutes being removed when converting Date object to plain string. Internally `JSON.stringify()` calls `Date.prototype.toJSON()` on Date objects to get a valid JSON representation of its value, and `toJSON()` is implemented to return the returned value of `Date.prototype.toISOString()`. So here I removed `JSON.stringify()` and made a direct call …
> Remove extra double quotes in ETAG inserted by JSON.stringify

- lib/ecstatic.js
- test/accept-encoding.js
This patch simply trims whitespace when checking the `accept-encoding` header. This header is split on commas, but this leaves a leading space on every element except the first, at least in Firefox and Chromium. By coincidence, this has been working because the first encoding in the list matches right away, but this behavior is not guaranteed.
Another way this could be done would be to split on `', '` (comma and space), and this would work in Firefox and Chromium for sure, but I don't believe this is guaranteed either. Using `.trim()` is safer since `'foo' === 'foo'.trim()`.
> Trim whitespace from request encoding headers

- lib/ecstatic.js
Currently a non-range request which is aborted will leak a file descriptor. This PR fixes that.
> fix: leak on res aborted on non-range requests

- lib/ecstatic.js
- package-lock.json
- package.json
Use on-finished. `close` is not always emitted in every scenario in some "older" versions of node. I don't remember the exact specifics.
> fix: on-finished

- CONTRIBUTORS.md
- README.md
- lib/bin.js
Added a "--host" option that you can use to specify the host (address) that Ecstatic listened to.
> Added "--host" option.

- lib/ecstatic.js
- package.json
Sorry for disturbing the peace of the dead, but I'd really appreciate you making an exception so I don't need to start a maintenance fork. (If you wish I do I might consider it though.)
> This fixes CVE-2019-10775. I'll postpone regression tests because
> the request library cannot send those requests (crashing the client
> instead of ecstatic), so I'll need to find another module that can.
> v4.1.3: [security] Fix crash on redirect with formfeed in URL (CVE-2019-10775)
